site_name: My FabAcademy 2025 Documentation
site_url: https://hannesjo.github.io/FabAcademy/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: black 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: grey
  font:
    text: Special Elite
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Pre Fab:
    - 0. Homepage: pre-fab/homepage.md
    - 1. Milling: pre-fab/milling.md
    - 2. PCB Design: pre-fab/pcb.md
    - 3. Brainstorming for Final Project: pre-fab/finalproject.md
  - Assignments:
    - 0. Overview: assignments/overview.md
    - 1. Principles and Practices: assignments/week01.md
    - 2. Computer-Aided Design: assignments/week02.md
    - 3. Computer-Controlled Cutting: assignments/week03.md
    - 4. Embedded Programming: assignments/week04.md
    - 5. 3D Scanning and Printing: assignments/week05.md
    - 6. Electronics Design: assignments/week06.md
    - 7. Computer-Controlled Machining: assignments/week07.md
    - 8. Electronics Production: assignments/week08.md
    - 9. Output Devices: assignments/week09.md
    - 10. Machine Week: assignments/week10.md
    - 11. Input Devices: assignments/week11.md
    - 12. Molding and Casting: assignments/week12.md
    - 13. Networking and Communications: assignments/week13.md
    - 14. Interface and Application Programming: assignments/week14.md
    - 15. Wild Card Week: assignments/week15.md
    - 16. Applications and Implications: assignments/week16.md
    - 17. Invention, Intellectual Property and Business Models: assignments/week17.md
    - 18-20. Project Development: assignments/week18.md
  - Final Project:
    - Overview: final-project/overview.md